INSERT INTO Pelaaja (nimi, aloitusvuosi, salasana) VALUES ('Matti Mainio', '2016', 'qwer');
INSERT INTO Pelaaja (nimi, aloitusvuosi, salasana) VALUES ('Minna Mainio', '2015', 'asdf');
INSERT INTO Pelaaja (nimi, aloitusvuosi, salasana) VALUES ('Mauno', '2017', 'Mauno');
INSERT INTO Pelaaja (nimi, aloitusvuosi, salasana) VALUES ('Minea', '2017', 'Minea');
INSERT INTO Pelaaja (nimi, aloitusvuosi, salasana) VALUES ('Miska Vuori', '2014', 'Miska');
INSERT INTO Pelaaja (nimi, aloitusvuosi, salasana) VALUES ('Mirva', '2016', 'Mirva');

INSERT INTO Aanestys (nimi, status, yllapitaja, kuvaus, julkaistu) VALUES ('Vuoden pelaaja', 'true', 1, 'vuoden parhain pelaaja', '2016-11-12');
INSERT INTO Aanestys (nimi, status, yllapitaja, kuvaus, julkaistu) VALUES ('Vuoden tyyli', 'true', 2, 'vuoden tyylikkäin pelitapa', '2015-11-12');
INSERT INTO Aanestys (nimi, status, yllapitaja, kuvaus, julkaistu) VALUES ('Vuoden tulokas', 'false', 1, 'vuoden tulokas', '2017-11-12');
INSERT INTO Aanestys (nimi, status, yllapitaja, kuvaus, julkaistu) VALUES ('Vuoden syöksyjä', 'true', 3, 'vuoden paras ja pelottomin syöksyjä', '2017-11-12');

INSERT INTO Ehdokas (pelaaja_id, aanestys_id) VALUES (1,1);
INSERT INTO Ehdokas (pelaaja_id, aanestys_id) VALUES (2,1);
INSERT INTO Ehdokas (pelaaja_id, aanestys_id) VALUES (3,1);
INSERT INTO Ehdokas (pelaaja_id, aanestys_id) VALUES (4,1);
INSERT INTO Ehdokas (pelaaja_id, aanestys_id) VALUES (5,1);
INSERT INTO Ehdokas (pelaaja_id, aanestys_id) VALUES (6,1);
INSERT INTO Ehdokas (pelaaja_id, aanestys_id) VALUES (1,2);
INSERT INTO Ehdokas (pelaaja_id, aanestys_id) VALUES (2,2);
INSERT INTO Ehdokas (pelaaja_id, aanestys_id) VALUES (3,2);
INSERT INTO Ehdokas (pelaaja_id, aanestys_id) VALUES (4,2);
INSERT INTO Ehdokas (pelaaja_id, aanestys_id) VALUES (5,2);
INSERT INTO Ehdokas (pelaaja_id, aanestys_id) VALUES (6,2);
INSERT INTO Ehdokas (pelaaja_id, aanestys_id) VALUES (1,3);
INSERT INTO Ehdokas (pelaaja_id, aanestys_id) VALUES (2,3);
INSERT INTO Ehdokas (pelaaja_id, aanestys_id) VALUES (3,3);
INSERT INTO Ehdokas (pelaaja_id, aanestys_id) VALUES (4,3);
INSERT INTO Ehdokas (pelaaja_id, aanestys_id) VALUES (5,3);
INSERT INTO Ehdokas (pelaaja_id, aanestys_id) VALUES (6,3);
INSERT INTO Ehdokas (pelaaja_id, aanestys_id) VALUES (1,4);
INSERT INTO Ehdokas (pelaaja_id, aanestys_id) VALUES (2,4);
INSERT INTO Ehdokas (pelaaja_id, aanestys_id) VALUES (3,4);
INSERT INTO Ehdokas (pelaaja_id, aanestys_id) VALUES (4,4);
INSERT INTO Ehdokas (pelaaja_id, aanestys_id) VALUES (5,4);
INSERT INTO Ehdokas (pelaaja_id, aanestys_id) VALUES (6,4);

INSERT INTO Aani(aanestaja_id, ehdokas_id, aanestys_id) VALUES(1, 1, 1);
INSERT INTO Aani(aanestaja_id, ehdokas_id, aanestys_id) VALUES(2, 1, 1);
INSERT INTO Aani(aanestaja_id, ehdokas_id, aanestys_id) VALUES(3, 1, 1);
INSERT INTO Aani(aanestaja_id, ehdokas_id, aanestys_id) VALUES(4, 2, 1);
INSERT INTO Aani(aanestaja_id, ehdokas_id, aanestys_id) VALUES(5, 2, 1);
INSERT INTO Aani(aanestaja_id, ehdokas_id, aanestys_id) VALUES(6, 3, 1);
INSERT INTO Aani(aanestaja_id, ehdokas_id, aanestys_id) VALUES(1, 2, 2);
INSERT INTO Aani(aanestaja_id, ehdokas_id, aanestys_id) VALUES(2, 1, 2);
INSERT INTO Aani(aanestaja_id, ehdokas_id, aanestys_id) VALUES(3, 4, 2);
INSERT INTO Aani(aanestaja_id, ehdokas_id, aanestys_id) VALUES(4, 2, 2);
INSERT INTO Aani(aanestaja_id, ehdokas_id, aanestys_id) VALUES(5, 1, 2);
INSERT INTO Aani(aanestaja_id, ehdokas_id, aanestys_id) VALUES(6, 1, 2);
INSERT INTO Aani(aanestaja_id, ehdokas_id, aanestys_id) VALUES(1, 1, 3);
INSERT INTO Aani(aanestaja_id, ehdokas_id, aanestys_id) VALUES(2, 2, 3);
INSERT INTO Aani(aanestaja_id, ehdokas_id, aanestys_id) VALUES(3, 4, 3);
INSERT INTO Aani(aanestaja_id, ehdokas_id, aanestys_id) VALUES(4, 1, 3);
INSERT INTO Aani(aanestaja_id, ehdokas_id, aanestys_id) VALUES(5, 1, 3);
INSERT INTO Aani(aanestaja_id, ehdokas_id, aanestys_id) VALUES(6, 1, 3);
INSERT INTO Aani(aanestaja_id, ehdokas_id, aanestys_id) VALUES(2, 2, 4);
INSERT INTO Aani(aanestaja_id, ehdokas_id, aanestys_id) VALUES(1, 2, 4);
INSERT INTO Aani(aanestaja_id, ehdokas_id, aanestys_id) VALUES(3, 1, 4);
INSERT INTO Aani(aanestaja_id, ehdokas_id, aanestys_id) VALUES(4, 5, 4);
INSERT INTO Aani(aanestaja_id, ehdokas_id, aanestys_id) VALUES(5, 1, 4);
INSERT INTO Aani(aanestaja_id, ehdokas_id, aanestys_id) VALUES(6, 2, 4);

