DROP TABLE IF EXISTS Pelaaja CASCADE;
DROP TABLE IF EXISTS Aanestys CASCADE;
DROP TABLE IF EXISTS Ehdokas CASCADE;
DROP TABLE IF EXISTS Aani CASCADE;-- Lisää DROP TABLE lauseet tähän tiedostoon
DROP TABLE IF EXISTS Pelaaja_harjoitus CASCADE;